server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: course-service-route
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**
        - id: media-service-route
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
