server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:34.29.246.228}:${DB_PORT:3306}/${DB_NAME:educloud_user_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:EduCloudSecurePass2026!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
